### ISSUE TITLE
Add URL redirect thingy

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/WorkshopHackathon2018#1]
Link blog post to `workshop.mdanalysis.org`

**Comment by orbeckst** [comment]
That's not working yet. Not sure why.

For testing I redirect to  https://github.com/MDAnalysis/WorkshopHackathon2018/ but https://workshop.mdanalysis.org is not recognized as a server. I added a `A` record but I think something is missing somewhere.

**Comment by orbeckst** [comment]
Now it works... the DNS just took a while. Let me know where to redirect to.

If we create a repo `MDAnalysis/workshop` and use its gh-pages branch (or switch it to publish the branch itself) then we can also just build a workshop site there. Or add a `gh-pages` branch to this repo, which will show up as https://www.mdanalysis.org/WorkshopHackathon2018.

**Comment by richardjgowers** [comment]
@orbeckst I'm not sure if the redirect should go to the signup form (#4 ) or the blog post (#3 )?  Maybe the latter, ie go read about it at workshop.mdanalysis.org (which contains a link to sign up)

**Comment by orbeckst** [comment]
The latter. 

Or if we build a mini site then to the mini site. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by richardjgowers** [comment]
@orbeckst blogpost is live at https://www.mdanalysis.org/2018/08/30/numfocus-workshop/

**Comment by orbeckst** [comment]
I changed the page forward rule to https://www.mdanalysis.org/2018/08/24/numfocus-workshop.

Tested that https://workshop.mdanalysis.org redirects properly.

**Comment by richardjgowers** [comment]
Thanks!
