### ISSUE TITLE
test cloud-based Jupyter instances

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#17]
Test JupyterHub instances (on AWS) that can be provided by Northwestern IT

- [ ] can install our python software stack 
  - MDAnalysis and deps
  - nglview ?
- [ ] can preload MDAnalysisData
- [ ] capacity for up to 60 participants?
- [ ] dask
  - can run dask with at least  multiprocessing tasks?
  - can run distributed with at least two workers?
  - bokeh web interface?

**Comment by kain88-de** [comment]
You considered updating the cloud image we provide on binder? https://mybinder.org/v2/gh/MDAnalysis/binder-notebook/master

**Comment by orbeckst** [comment]
We should, no matter what else we do here. Especially once MDAnalysisData is also on conda https://github.com/MDAnalysis/MDAnalysisData/issues/21

**Comment by orbeckst** [comment]
@richardjgowers @micaela-matta forgot to ask on the call: is your jupyterhub solution going to work as a backup? – Can this be closed?

**Comment by richardjgowers** [comment]
we tested this today and it works, I didn’t check desk though

**Comment by micaela-matta** [comment]
> We installed the following packages:
>mdanalysis
>mdanalysisdata
>mdanalysistests
>pmda

**Comment by micaela-matta** [comment]
we're taking care of the dependencies right now.
