### ISSUE TITLE
test MDAnalysis on windows

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#18]
1. follow current installation instructions for environment on Windows
2. use new Windows conda package https://github.com/MDAnalysis/mdanalysis/issues/2116 
3. work through tutorials and see if they break; make notes!

blocked on: https://github.com/MDAnalysis/mdanalysis/issues/2116

**Comment by orbeckst** [comment]
@VOD555 did you test the windows conda ?

**Comment by VOD555** [comment]
@orbeckst I've tested the windows conda, and it works well with the conda installation for MDA. But I haven't test the condition without visual studio installed.

**Comment by orbeckst** [comment]
Working since MDA 0.19.2
