### ISSUE TITLE
dask tutorial

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#20]
introductory tutorial on dask
- background: task graph and execution
- parallelizing with dask
- using distributed (setting up a dask cluster)
- using the bokeh status web interface

**Comment by orbeckst** [comment]
@VOD555 please coordinate with @dotsdl for your PMDA tutorial so that the two tutorials fit together.

**Comment by orbeckst** [comment]
With the changes in https://github.com/MDAnalysis/pmda/pull/66 and the new way to globally define the scheduler it becomes even more useful to have a solid introduction to dask. 

@dotsdl please can you make sure that the [new idiom to set the scheduler](http://docs.dask.org/en/latest/scheduling.html#configuration), which @kain88-de explained in https://github.com/MDAnalysis/pmda/pull/66#issuecomment-434417794, is also covered?

**Comment by orbeckst** [comment]
With PMDA now using dask's preferred way to select a scheduler, we now have to teach people to explicitly set the *multiprocessing* or *distributed* scheduler and _not_ the default *threaded* scheduler. Threaded does not work well with our largely Python based code.

**Comment by kain88-de** [comment]
If people don’t change the scheduler setting we pick multiprocessing. We
should add to the pmda docs that thread scheduler doesn’t work with pmda.

**Comment by orbeckst** [comment]
Yes, you're right. 

(I didn't think of adding ad note regarding the threaded scheduler in https://github.com/MDAnalysis/pmda/issues/78.)
