### ISSUE TITLE
PMDA tutorial

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#21]
introduction to PMDA
- background, refer back to dask tutorial #20 
- using existing classes
- writing your own

**Comment by orbeckst** [comment]
@micaela-matta you set the figshare above to "private visibility" but by providing the link above everyone can see it nevertheless. You might as well make it public...

**Comment by micaela-matta** [comment]
@orbeckst  I am running another 20ns, so until that's done I want to be able to modify the trajectory to include more frames. In the meantime people can have a play.
