### ISSUE TITLE
git tutorial

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#22]
Very brief introduction (or refresher) for `git` (needed for hackathon).

Use the SWC git tutorial https://swcarpentry.github.io/git-novice/ as basis.

**Comment by micaela-matta** [comment]
a cool thing to demo during the git part would be to resolve an (easy) issue from the many MDAnalysis (real) ones or create one that we know how to solve. @richardjgowers could show the entire thing from start to finish. if you have suggestions on which issue we could pick, let us know!

**Comment by richardjgowers** [comment]
Plz only easy issues
