### ISSUE TITLE
info-pack email

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#26]
Send instructions to participants that include
- how to get there
- contact (mobile number...)
- installation instructions #9 

Send at 
- 2 weeks (Mo 10/29/2018)
- 1 week (Mo 11/5/2018)
- 2 days (Fri 11/9/2018)

**Comment by micaela-matta** [comment]
1st round sent.

**Comment by micaela-matta** [comment]
2nd round sent as soon as @richardjgowers finished testing the windows conda package
