### ISSUE TITLE
advanced tutorials

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#28]
Notebooks for advanced topics and self-guided study

- visualization with nglview
- PDB focus
  - include intro to PDB attributes (using occupancy – see [MDA Tutorial: b-factors](https://www.mdanalysis.org/MDAnalysisTutorial/writing.html#example-saving-dynamic-per-atom-properties-in-b-factor))
  - fetch_MMTF
- Universe building
  - Universe.empty
  - adding new topology attrs
- Advanced Universe creation 
  - in memory
  - guess bonds
- Writing a custom Reader class

The h-bonding case study is listed separately #25.

**Comment by richardjgowers** [comment]
@dotsdl is there an existing datreant tutorial notebook? I know there's the scipy talk on youtube..

**Comment by micaela-matta** [comment]
I can make one on π-stacking/ using networkx
