### ISSUE TITLE
live tweeting and photos

### ISSUE THREAD

**Issue by micaela-matta** [MDAnalysis/WorkshopHackathon2018#40]
we should probably have someone live tweeting the event and posting photos.
I will bring my camera to take photos (we want to show how well attended the event is, and how we spend the grant $!), but we'd need someone with access to the MDAnalysis twitter account.

**Comment by kain88-de** [comment]
Richard and Oliver have access.

**Comment by orbeckst** [comment]
Now @richardjgowers has too.

And we did, see https://twitter.com/mdanalysis
