### ISSUE TITLE
swag?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#6]
How about custom USB sticks with logo https://www.customusb.com/gem-flash-drive/ (laser engraved and embedded in translucent plexiglass for maximum geekness) and software + paper + workshop materials (trajectories??)  pre-loaded 

Max 100 MB can be preloaded by the manufacturer so we could have a base installation pre-loaded (not sure what to include – miniconda and pip packages??) and then we manually add workshop materials.

Cost (for 35):
- $7.57 / pc
- 16 GB (we can go lower but 1 GB is $7.05 instead of $7.57)
- USB 2.0 (a bit lame...)

Alternative swag
- mouse mat with MDAnalysis cheat sheet (@richardjgowers favorite)
- mug
- stickers (still have some)
- fridge magnets (still have some)

cc: @richardjgowers @micaela-matta

**Comment by orbeckst** [comment]
The logos are also in the doc tree under https://github.com/MDAnalysis/mdanalysis/tree/develop/package/doc/sphinx/source/_static/logos including PDF versions.

![mdanalysis-logo](https://user-images.githubusercontent.com/237980/44677356-95795b80-a9ea-11e8-87a9-155524547b2d.png)
![mdanalysis-logo_square](https://user-images.githubusercontent.com/237980/44677373-9f02c380-a9ea-11e8-87a5-632ab16d12e3.png)

**Comment by richardjgowers** [comment]
I've gone off the USB idea, I'm not sure when I last used one.  I wouldn't really trust someone to preload them properly either..

I like visible things, so stickers and magnets are cool.

We should do a MDA cheat sheet ([like these](https://www.datacamp.com/community/blog/python-numpy-cheat-sheet)), but they're cheap to print so the real time limiting step is designing it.

**Comment by micaela-matta** [comment]
I would like mugs/water bottles and tote bags (cheaper). we can surely ask around NU for their preferred (cheap?) swag providers.

**Comment by orbeckst** [comment]
Water bottles are great for AZ. But I also like mugs. 

Can you get an idea for the price?

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
@richardjgowers please close when done
