### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/WorkshopHackathon2018#9]
We need a single set of installation instructions as a web page.

The installation instructions (link) will be send as part of the info pack email. 

## Environment
- Python (conda: anaconda installation)
   - Python 3.5+
   - Jupyter, numpy
- bash (for hackathon)
- git (for hackathon)
- editor: atom (for hackathon)

See for example
- http://smallerthings.org/pages/2017-02-15-learn-data-science
- http://asu-compmethodsphysics-phy494.github.io/ASU-PHY494/2018/01/09/00_Setting_up_the_environment/

## Conda Packages
- [x] MDAnalysis
   - Linux
   - Mac OS X/macOS
   - Windows (!) https://github.com/MDAnalysis/mdanalysis/issues/2116
- [x] PMDA https://github.com/MDAnalysis/pmda/issues/74
- [x] MDAnalysisData https://github.com/MDAnalysis/MDAnalysisData/issues/21
  - [x] dask (dependency of MDAnalysisData)
  

## Old installation instructions
For comparison, see what we had for 
* [MDAnalysisTutorial](https://www.mdanalysis.org/MDAnalysisTutorial/installation.html)
*  [CECAM 2015 Workshop](https://becksteinlab.github.io/MDAnalysis-workshop/index.html)
* [SPIDAL-MDAnalysis Tutorial](https://www.mdanalysis.org/SPIDAL-MDAnalysis-Midas-tutorial/installation.html)

**Comment by orbeckst** [comment]
I updated the requirements for installation instructions after today's conference call.

**Comment by orbeckst** [comment]
I updated the issue after yesterday's conference call.

@dotsdl already started with [INSTALL.md](https://github.com/MDAnalysis/WorkshopHackathon2018/blob/master/INSTALL.md).

**Comment by dotsdl** [comment]
Continuing on this tomorrow evening. Thanks @orbeckst for laying out the requirements!

**Comment by dotsdl** [comment]
@richardjgowers @orbeckst are we good to proceed with Python 3.7? I don't think we currently test for this in [Travis](https://github.com/MDAnalysis/mdanalysis/blob/develop/.travis.yml).

**Comment by orbeckst** [comment]
Although 3.7 should work in principle, I'd rather go with 3.6 which is extensively tested. 

There's an issue or PR to add 3.7 to the test matrix but I forgot what the status is. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by kain88-de** [comment]
conda-forge is still updating everything for python 3.7. [status](https://conda-forge.org/status/). It is combined with a switch to the new compiler infrastructure in conda. They are making good progress but they don't have as much CI time as they would like and *a lot* of packages to update.

**Comment by dotsdl** [comment]
Ah okay, we'll instruct participants to install 3.6 then. Agreed.

**Comment by richardjgowers** [comment]
@dotsdl some feedback, roughly from top to bottom on the installation instructions:

Can we say that people need Anaconda, rather than Python?

Also from my Windows 10 VM, there's an "anaconda shell" which seems to be good enough to do simple command line things from

From Windows it looks like there's a start menu shortcut to Jupyter notebook (inbetween the Candy Crush shortcuts) which might be the best way to launch this?

In which case, are we even using a bash shell at all?  Most stuff is from notebooks, git interaction can be via Atom I think.. only thing I can think of is running pytest, but surely that can be via the "IDE" too..

**Comment by VOD555** [comment]
@dotsdl @richardjgowers Windows version Anaconda has a navigator which contains Jupyter notebook. And we can do `pip install` or `conda install` using the Anaconda prompt("anaconda shell"). 

Current problem is that we don't have a windows conda installation for MDAnalysis and PMDA. It seems that Microsoft Visual C++ 14.0 is required to install MDAnalysis using `pip install`. (I'm not sure whether C++ 14.0 is required if we use `conda install`.)

**Comment by richardjgowers** [comment]
@VOD555 Yeah I've managed to pip install a source distribution of MDAnalysis on Windows with visual c++ 14 too.  Ideally we get a Windows conda build working...

**Comment by kain88-de** [comment]
@richardjgowers if you make a minor release of MDA we can publish a windows build on conda-forge.

**Comment by kain88-de** [comment]
The data package is now also on conda forge. Everything is now conda installable.

**Comment by orbeckst** [comment]
@kain88-de thanks for PR #29 – merged.

**Comment by orbeckst** [comment]
https://github.com/MDAnalysis/WorkshopHackathon2018/issues/9#issuecomment-433640230
> Can we say that people need Anaconda, rather than Python?

Yes, although we should really say that we install it for a full Python-based scientific computing software stack.

> In which case, are we even using a bash shell at all? Most stuff is from notebooks, git interaction can be via Atom I think.. only thing I can think of is running pytest, but surely that can be via the "IDE" too..

I am not familiar with any of these shells and my experience is, that once something goes wrong, you just want to open a config file in `vi` or run the shell commands that you know work. We don't have to spend time teaching the shell, I think, but it should be there (and git-bash makes it easy!)

We don't have to emphasize the shell but I think it will make our life easier having it. It also allows us to give people (almost) identical instructions across Windows, macOS, and Linux.

**Comment by orbeckst** [comment]
The installation instructions don't render nicely in GitHub markdown because of highlight sections. We should put them into a website. Should we use Jekyll as static site generator (possibly using the MDA theme)? Or use Sphinx (like the [SPIDAL-MDAnalysis tutorial](https://www.mdanalysis.org/SPIDAL-MDAnalysis-Midas-tutorial/) but then this has to be recoded into reST. @dotsdl ?

**Comment by micaela-matta** [comment]
WRT the shell: the majority of attendees already have some familiarity with python, so I think it's ok to assume that most of them, being PhD students, are already (becoming) familiar with the terminal

> 
> > In which case, are we even using a bash shell at all? Most stuff is from notebooks, git interaction can be via Atom I think.. only thing I can think of is running pytest, but surely that can be via the "IDE" too..
> 
> I am not familiar with any of these shells and my experience is, that once something goes wrong, you just want to open a config file in `vi` or run the shell commands that you know work. We don't have to spend time teaching the shell, I think, but it should be there (and git-bash makes it easy!)
> 
> We don't have to emphasize the shell but I think it will make our life easier having it. It also allows us to give people (almost) identical instructions across Windows, macOS, and Linux.

**Comment by orbeckst** [comment]
@dotsdl please check the formatting, https://www.mdanalysis.org/WorkshopHackathon2018/INSTALL is garbled towards the end.

**Comment by orbeckst** [comment]
- fixed formatting,
- also link to our own wiki pages
- added wiki page for [*downloading data*](https://github.com/MDAnalysis/WorkshopHackathon2018/wiki/download-data) and linked to it
